package hclread

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
	"strings"

	"github.com/hashicorp/hcl/v2"
	"github.com/spf13/afero"
	"github.com/walteh/terrors"
	"github.com/walteh/yaml"
)

func Process(ctx context.Context, fs afero.Fs, file string) (*FileBlockEvaluation, hcl.Diagnostics, error) {
	opn, err := afero.ReadFile(fs, file)
	if err != nil {
		return nil, nil, err
	}

	_, ectx, blks, diags, err := NewContextFromFile(ctx, opn, file)
	if err != nil || diags.HasErrors() {
		return nil, diags, err
	}

	eval, diags, err := NewGenBlockEvaluation(ctx, ectx, blks)
	if err != nil || diags.HasErrors() {
		return nil, diags, err
	}

	return eval, diags, nil
}

func (me *FileBlockEvaluation) WriteToFile(ctx context.Context, fs afero.Fs) error {
	out, erry := me.WriteToReader(ctx)
	if erry != nil {
		return terrors.Wrapf(erry, "failed to encode block %q", me.Name)
	}

	if err := fs.MkdirAll(filepath.Dir(me.Path), 0755); err != nil {
		return terrors.Wrapf(err, "failed to create directory %q", me.Path)
	}

	if err := afero.WriteReader(fs, me.Path, out); err != nil {
		return terrors.Wrapf(err, "failed to write file %q", me.Name)
	}

	return nil
}

func (me *FileBlockEvaluation) WriteToReader(ctx context.Context) (io.Reader, error) {
	out, erry := me.Encode()
	if erry != nil {
		return nil, terrors.Wrapf(erry, "failed to encode block %q", me.Name)
	}

	return bytes.NewReader(out), nil
}

func (me *FileBlockEvaluation) Encode() ([]byte, error) {

	arr := strings.Split(me.Path, ".")
	if len(arr) < 2 {
		return nil, terrors.Errorf("invalid file name [%s] - missing extension", me.Name)
	}

	header := fmt.Sprintf(`# code generated by retab. DO NOT EDIT.
# join the fight against yaml @ github.com/walteh/retab

# source: %q

`, me.Source)

	switch arr[len(arr)-1] {
	case "jsonc":
		return json.MarshalIndent(me.OrderedOutput, "", "\t")
	case "json":
		return json.MarshalIndent(me.OrderedOutput, "", "\t")
	case "yaml", "yml":
		buf := bytes.NewBuffer(nil)
		enc := yaml.NewEncoder(buf)
		// enc.SetIndent(4)
		defer enc.Close()

		err := enc.Encode(me.OrderedOutput)
		if err != nil {
			return nil, err
		}

		strWithTabsRemovedFromHeredoc := strings.ReplaceAll(buf.String(), "\t", "")

		return []byte(header + strWithTabsRemovedFromHeredoc), nil

	default:
		return nil, terrors.Errorf("unknown file extension [%s] in %s", arr[len(arr)-1], me.Name)
	}
}
