{
    inpackage: false,
    with-expecter: true,
    testonly: false,
    exported: true,
    outpkg: mockery,
    filename: "{{.InterfaceName}}.{{.PackageName}}.mockery.go",
    mockname: "Mock{{.InterfaceName}}_{{.PackageName}}",
    packages:
        {
            github.com/walteh/retab/pkg/configuration:
                { interfaces: { Configuration: {} } },
        },
}
