inpackage: false
with-expecter: true
testonly: false
exported: true
outpkg: "{{.PackageName}}mock"
dir: ./gen/mocks/{{.InterfaceDirRelative}}mock
disable-version-string: true
resolve-type-alias: false
issue-845-fix: true
filename: "{{.InterfaceName}}_mock.gen.go"
mockname: Mock{{.InterfaceName}}
packages: # generated
  github.com/walteh/retab/v2/pkg/format:
    interfaces:
      Configuration: {}
