#!/usr/bin/env sh

set -e

: "${DESTDIR=./bin/build}"
# : "${PACKAGE=}"
: "${VERSION=$(./hack/git-meta version)}"
: "${REVISION=$(./hack/git-meta revision)}"

: "${CGO_ENABLED=0}"
: "${GO_PKG=}"
: "${GO_EXTRA_FLAGS=}"
: "${GO_LDFLAGS=-X ${GO_PKG}/version.Version=${VERSION} -X ${GO_PKG}/version.Revision=${REVISION} -X ${GO_PKG}/version.Package=${GO_PKG}}"
: "${GO_EXTRA_LDFLAGS=}"

set -x
CGO_ENABLED=$CGO_ENABLED go build -mod vendor -trimpath ${GO_EXTRA_FLAGS} -ldflags "${GO_LDFLAGS} ${GO_EXTRA_LDFLAGS}" -o "${DESTDIR}/tftab" ./cmd
