#!/usr/bin/env sh

set -e

: "${DESTDIR=./bin/build}"
: "${BIN_REVISION=local}"
: "${BIN_NAME=local}"
: "${BIN_VERSION=local}"

: "${CGO_ENABLED=0}"
: "${GO_PKG=}"
: "${GO_EXTRA_FLAGS=}"
: "${GO_LDFLAGS=-X ${GO_PKG}/version.Version=${BIN_VERSION} -X ${GO_PKG}/version.Revision=${BIN_REVISION} -X ${GO_PKG}/version.Package=${GO_PKG}}"
: "${GO_EXTRA_LDFLAGS=}"

CGO_ENABLED=$CGO_ENABLED go build -mod vendor -trimpath ${GO_EXTRA_FLAGS} -ldflags "${GO_LDFLAGS} ${GO_EXTRA_LDFLAGS}" -o "${DESTDIR}/${BIN_NAME}" ./cmd
