#!/usr/bin/env bash

set -eu -o pipefail

: "${DESTDIR=./bin/release}"

if [ ! -d "$DESTDIR" ]; then
	exit 0
fi

# checksums
(
	cd ${DESTDIR}
	# Use find command to get all files except those with .json extension
	find . -type f ! \( -name '*.json' -o -name '*.txt' \) -exec sha256sum -b {} \; >./checksums.txt
	# Optionally, remove lines containing "darwin" if needed
	sed -i '/darwin/d' ./checksums.txt
	sha256sum -c --strict checksums.txt
)
