// Code generated by mockery v2.32.4. DO NOT EDIT.

package mockery

import mock "github.com/stretchr/testify/mock"

// MockConfigurationProvider is an autogenerated mock type for the Provider type
type MockConfigurationProvider struct {
	mock.Mock
}

type MockConfigurationProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigurationProvider) EXPECT() *MockConfigurationProvider_Expecter {
	return &MockConfigurationProvider_Expecter{mock: &_m.Mock}
}

// IndentSize provides a mock function with given fields:
func (_m *MockConfigurationProvider) IndentSize() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockConfigurationProvider_IndentSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndentSize'
type MockConfigurationProvider_IndentSize_Call struct {
	*mock.Call
}

// IndentSize is a helper method to define mock.On call
func (_e *MockConfigurationProvider_Expecter) IndentSize() *MockConfigurationProvider_IndentSize_Call {
	return &MockConfigurationProvider_IndentSize_Call{Call: _e.mock.On("IndentSize")}
}

func (_c *MockConfigurationProvider_IndentSize_Call) Run(run func()) *MockConfigurationProvider_IndentSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurationProvider_IndentSize_Call) Return(_a0 int) *MockConfigurationProvider_IndentSize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigurationProvider_IndentSize_Call) RunAndReturn(run func() int) *MockConfigurationProvider_IndentSize_Call {
	_c.Call.Return(run)
	return _c
}

// UseTabs provides a mock function with given fields:
func (_m *MockConfigurationProvider) UseTabs() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockConfigurationProvider_UseTabs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UseTabs'
type MockConfigurationProvider_UseTabs_Call struct {
	*mock.Call
}

// UseTabs is a helper method to define mock.On call
func (_e *MockConfigurationProvider_Expecter) UseTabs() *MockConfigurationProvider_UseTabs_Call {
	return &MockConfigurationProvider_UseTabs_Call{Call: _e.mock.On("UseTabs")}
}

func (_c *MockConfigurationProvider_UseTabs_Call) Run(run func()) *MockConfigurationProvider_UseTabs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigurationProvider_UseTabs_Call) Return(_a0 bool) *MockConfigurationProvider_UseTabs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigurationProvider_UseTabs_Call) RunAndReturn(run func() bool) *MockConfigurationProvider_UseTabs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigurationProvider creates a new instance of MockConfigurationProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigurationProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigurationProvider {
	mock := &MockConfigurationProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
