// Code generated by options-gen. DO NOT EDIT.
package diff

import (
	"github.com/google/go-cmp/cmp"
)

type OptTestingOptsSetter func(o *TestingOpts)

func NewTestingOpts(
	options ...OptTestingOptsSetter,
) TestingOpts {
	o := TestingOpts{}

	// Setting defaults from field tag (if present)

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithCmpOpts(opt []cmp.Option) OptTestingOptsSetter {
	return func(o *TestingOpts) {
		o.cmpOpts = opt

	}
}

func (o *TestingOpts) Validate() error {
	return nil
}
